// backend/src/main/resources/templates/frontend/react/App.jsx
import { useState, useEffect } from 'react'
import axios from 'axios'

function App() {
  const [message, setMessage] = useState('Loading...')

  useEffect(() => {
    axios.get('/api/hello')
      .then(res => setMessage(res.data.message))
      .catch(err => setMessage('Error: ' + err.message))
  }, [])

  return (
    <div className="app">
      <h1>{{PROJECT_NAME}}</h1>
      <p>{message}</p>
    </div>
  )
}

export default App

// backend/target/classes/templates/frontend/vue/App.vue
<template>
  <div style="text-align: center; margin-top: 50px">
    <h1>{{PROJECT_NAME}}</h1>
    <p>{{ message }}</p>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'

const message = ref('Loading...')

onMounted(async () => {
  try {
    const res = await fetch('/api/hello')
    const data = await res.json()
    message.value = data.message
  } catch {
    message.value = '{{PROJECT_NAME}} — Frontend is running!'
  }
})
</script>
